services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ganaderia
      DB_USER: ganaderia
      DB_PASSWORD: 1100
      JWT_SECRET: clave_secreta_ganaderia_2026
      PORT: 8000

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ganaderia
      POSTGRES_PASSWORD: 1100
      POSTGRES_DB: ganaderia
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backend/models/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ganaderia -d ganaderia"]
      interval: 5s
      timeout: 5s
      retries: 5
